config/routes.rb
Rails.application.routes.draw do

  root 'board#index'

  resources :board

  resources :artist 
  
  resources :song

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    
    has_many :songs

end

app/models/billboard.rb
class Billboard < ApplicationRecord

    has_many :songs

end

app/models/song.rb
class Song < ApplicationRecord

    belongs_to :artist
    belongs_to :billboard

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index

  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def edit
  end
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy]
  
  def index
    @board = Billboard.all
  end

  def show
  end

  def new 
    @board = Billboard.new
  end

  def create
    @board = Billboard.new(board_params)
    
    if @board.save
      redirect_to board_path
    else
      render :new
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to @board
    else 
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to board_path
  end

  private 
    def set_board
    @board = Billboard.find(params[:id])
    end

    def board_params
    params.require(:board).permit(:ustop, :eurotop, :top)
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @song = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      flash[:info] = "Song Saved"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  private
    def song_params
      params.require(:title).permit(:genre)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/board/_form.html.erb
<%= form_with(model: billboard, local: true, class: "ui form") do |f| %>
    <div class="field">
      <%= f.label :ustop %>
      <%= f.text_field :ustop, required: true, placeholder: "US Top 100" %>
    </div>
    <div class="field">
      <%= f.label :eurotop %>
      <%= f.text_field :eurotop, required: true, placeholder: "Euro Top 100" %>
    </div>
    <div class="field">
      <%= f.label :top %>
      <%= f.text_field :top, required: true, placeholder: "Top" %>
    </div>
<% end %>

app/views/board/edit.html.erb
<h1>Edit Billboard</h1>

<%= render "form", board: @board %>

<%= link_to "Show", board_path(@zoo) %>
<%= link_to "Back", board_path %>

app/views/board/index.html.erb
<div class="container text-center">
  <h1>Music Billboard</h1>
  <div class="row">
  <div class="col-md-4">
    US TOP 100
  </div>
  <div class="col-md-4">
    EURO TOP 100
  </div>
  <div class="col-md-4">
    TOP 50 
  </div>
</row>
<br>
<br>
<br>
  <% @board.each do |board| %>
  <h1><%= board.name %></h1>
    <%= link_to "Show", board_path(person) %>
    <%= link_to "Edit", edit_board_path(person) %>
    <%= link_to "Destroy", board_path(person), method: :delete %>
<% end %>
  <br />
<%= link_to "New Billboard", new_board_path %>
<%= link_to "Add New Song", songs_new_path %>

app/views/board/new.html.erb
<h1>New Billboard</h1>

<%= render "form", board: @board %>

<%= link_to "Back", board_path %>

app/views/board/show.html.erb
<div class="ui card">
    <div class="content">
        <p class="header">
            <%= @board.name %>
        </p>
    </div>
    <div class="extra content">
        <% link_to 'Edit', edit_board_path(@board) %> |
        <%= link_to 'Back', board_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Add New Song</h1>




<%= simple_form_for @song, :url => new_song_path, :method => :get do |f| %>
<%# simple_form_for(@song, html: { class: 'form-inline' }) do |f| %>

    <%= f.input :title, label: "Song Title/Name of Piece", placeholder: "Be sure spelling is correct" %>
    
    <%= f.submit "Post it!", class: 'my-btn' %>

<% end %>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>